name: dlox
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  path: ^1.8.0
  analyzer_utils:
    path: /Users/pattobrien/dev/pattobrien/analyzer-utils

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
