name: dlox
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  path: ^1.8.0
  analyzer_utils:
    path: /Users/pattobrien/dev/pattobrien/analyzer-utils
  code_builder: ^4.10.0
  recase: ^4.1.0
  dart_style: ^2.3.4
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
